export const mainContent = 'main-content'
export const homeValues = 'home-value'
export const homeHiw = 'home-hiw'
export const about = 'about'
export const messages = 'messages'
export const artworkTypes = 'artwork-types'
export const artworks = 'artworks'
